PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?personId ?personFirstName ?personLastName (count(?comment) as replyCount) ?tagNames
WHERE{

      ?friend   snvoc:id         ?personId;
                snvoc:firstName  ?personFirstName;
                snvoc:lastName   ?personLastName.
      ?comment  snvoc:hasCreator ?friend;
                snvoc:replyOf    ?post.
      ?post     snvoc:hasTag     ?tag.
      ?tag      foaf:name        ?tagNames;
                rdf:type         ?tagClass.
      ?tagClass rdfs:subClassOf*  ?tagParent.
      ?tagParent rdfs:label       $TagType.
      {
        SELECT ?friend
        WHERE {
            ?someone snvoc:knows ?tfr;
                     snvoc:id    $Person.
            ?tfr     snvoc:hasPerson ?friend.
        }
      }
}
#GROUP BY ?personId ?personFirstName ?personLastName ?tagNames
ORDER BY DESC(?replyCount) ASC(?personId)
