PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>

SELECT ?person ?first ?last ?tag (sum(?Count) as ?replyCount)
WHERE{
  ?post snvoc:hasTag ?tag.
  ?tag  snvoc:isSubclassOf* ?TagClass.
  ?person snvoc:firstName ?first;
          snvoc:lastName  ?last.
  {
    SELECT ?post (count(?comment) as ?Count)
    WHERE {
      ?comment snvoc:hasCreator ?friend;
               snvoc:replyOf    ?post.
      {
        SELECT DISTINCT ?friend
        WHERE {
            ?person snvoc:knows ?tfr.
            ?tfr    snvoc:hasPerson ?friend.
        }
      }
    }
    GROUP BY ?post
  }
}
GROUP BY ?tag ?person ?first ?last
ORDER BY DESC(?replyCount) ASC(?person)
LIMIT 10