PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>

SELECT DISTINCT ?friend ?first ?last ?message ?content ?cdate
WHERE {
  ?friend  snvoc:firstName ?first;
           snvoc:lastName  ?last.
  ?message snvoc:hasCreator   ?friend;
           snvoc:creationDate ?cdate.
  {
    SELECT DISTINCT ?friend
    WHERE {
      {
        ?person snvoc:knows ?tfr.
        ?tfr    snvoc:hasPerson ?friend.
      } union {
        ?person snvoc:knows ?tfr2.
        ?tfr2   snvoc:hasPerson ?fr2.
        ?fr2    snvoc:knows ?tfr.
        ?tfr    snvoc:hasPerson ?friend.
        filter (?friend != ?person)
      } .
    }
  }
  FILTER (?cdate < ?date )
  {{?message snvoc:content ?content} union {?message snvoc:imageFile ?content}} .
}
ORDER BY DESC(?creationDate) ASC(?message)