prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
prefix sntag: <http://www.ldbc.eu/ldbc_socialnet/1.0/tag/>
prefix sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix dbpedia: <http://dbpedia.org/resource/>
prefix dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT  (?oID AS ?otherID)
        (?fn AS ?firstName)        (?ln AS ?lastName)
        (?lcd AS ?likeCreationDate)
        (?mID AS ?commentOrPostID)
        (?cont AS ?commentOrPostContent)
        (((?lcd - ?mcd)/60) AS ?minutesLatency)
        ((NOT EXISTS {?oPer snvoc:knows/snvoc:hasPerson ?gPer}) AS ?isNew)
WHERE {
?gPer           snvoc:id                ?id .
?message        snvoc:id                ?mID;
                snvoc:creationDate      ?mcd;
                snvoc:hasCreator        ?gPer .

{?message snvoc:content ?cont}
UNION
{?message snvoc:imageFile ?cont} .

?likes          snvoc:creationDate      ?lcd .

{?likes snvoc:hasPost ?message}
UNION
{?likes snvoc:hasComment ?message}

?oPer           snvoc:likes             ?likes;
                snvoc:id                ?oID;
                snvoc:firstName         ?fn;
                snvoc:lastName          ?ln .
}
ORDER BY DESC(?lcd) ?oID
LIMIT 20